# -*- coding: utf-8 -*-
#
# This file is part of the Rosenberg NMS
#
# Copyright (C) 2011-2013 Craig Small <csmall@enc.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses/>
#
#
"""This file contains the database entries that are used for intially filling
the database"""
from rnms.lib.states import *

alarm_states = (
    (u'down', 10, 'down.wav', 'up.wav', STATE_DOWN),
    (u'up', 100, '', '', STATE_UP), 
    (u'alert', 60, 'boing.wav', '', STATE_ALERT), 
    (u'testing', 40, '', '', STATE_TESTING), 
    (u'running', 100, '', '', STATE_UP), 
    (u'not running', 20, '', '', STATE_DOWN), 
    (u'open', 100, '', '', STATE_UP), 
    (u'closed', 15, '', '', STATE_DOWN), 
    (u'error', 90, 'boing.wav', '', STATE_ALERT), 
    (u'invalid', 30, '', '', STATE_DOWN), 
    (u'valid', 110, '', '', STATE_UP), 
    (u'reachable', 100, '', '', STATE_UP), 
    (u'unreachable', 5, '', '', STATE_DOWN), 
    (u'lowerlayerdown', 10, 'down.wav', 'up.wav', STATE_DOWN), 
    (u'synchronized', 100, '', '', STATE_UP), 
    (u'unsynchronized', 6, '', '', STATE_DOWN), 
    (u'battery normal', 100, '', '', STATE_UP), 
    (u'battery low', 4, '', '', STATE_DOWN), 
    (u'battery unknown', 2, '', '', STATE_DOWN), 
    (u'on battery', 3, '', '', STATE_DOWN), 
    (u'on line', 90, '', '', STATE_UP), 
    (u'ok', 100, '', '', STATE_UP), 
    (u'out of bounds', 10, '', '', STATE_DOWN), 
    (u'unavailable', 10, 'down.wav', 'up.wav', STATE_DOWN), 
    (u'available', 100, '', '', STATE_UP), 
    (u'battery depleted', 3, '', '', STATE_DOWN), 
    (u'other', 10, '', '', STATE_DOWN), 
    (u'unknown', 10, '', '', STATE_DOWN), 
    (u'noncritical', 90, '', '', STATE_DOWN), 
    (u'critical', 10, '', '', STATE_DOWN), 
    (u'nonrecoverabl', 10, '', '', STATE_DOWN), 
    (u'warning', 80, 'down.wav', 'up.wav', STATE_DOWN)
    )

autodiscovery_policies = (
    (u'No Autodiscovery', True,False,False,False,False,False, True, True, True),
    (u'Standard'        , True, True,False, True,False, True, True, True, True),
    (u'Automagic'       , True, True, True, True, True,False, True, True, True),
    (u'Administrative'  ,False, True, True, True,False, True, True, True, True),
    (u'Just Inform'     ,False,False,False, True,False,False,False, True, True),
    (u'Standard (for Switches)', True, True,False, True, True,False, True, True,False)
    )
#showable 2=1,0 1=1,1 0=0,0
#RRD Types = 1:gauge, 2:counter, 3:absolute
attribute_types = (
        (u'No Interface Type',
            'none', '', False, False,
            u'No Polling', '', '',
            'AVERAGE',103680, False, False, '', 
                () , () ),
        (u'TCP Ports',
            'tcp_ports','500,600-1024', False, True,
            u'TCP/IP Port', '', '',
            'LAST',103680, True, True, '', (
            ('Port Number','port',False, True, True, True, False, '0','',''),
            ('Check Content','check_content',False, True, False, True, False,'0','',''),
            ('Check Content URL','check_url',False, True, True, False, True, '','',''),
            ('Check Content RegExp','check_regexp',False, True, False, True, False, '','','')
            ), (
            (u'Established Connections', 'tcp_established', 0,0,10000,0),
            (u'Connection Delay', 'conn_delay', 0,0,10000,0),
            ) ),
        (u'Cisco System Info',
            'host_information','cisco,9.1,9.5',True, True,
            u'Cisco Router', '', '',
            'AVERAGE',103680,False, False,'ent.9',(
            ('Number of Processors','cpu_num',False, True, True, True, False, '1','',''),
            ('CPU Usage Threshold','cpu_threshold',False, True, False, True, False, '60','',''),
            ('System Name','name',True, True, True, True, False, '','',''),
            ('Location','location',True, True, True, True, False, '','',''),
            ('Contact','contact',True, True, True, True, False, '','',''),
           ), (
            (u'CPU', 'cpu', 0,0,100,''),
            (u'Mem Used', 'mem_used', 0,0,100000000000,''),
            (u'Mem Free', 'mem_free', 0,0,100000000000,''),
            (u'Acct Packets', 'acct_packets', 2,0,100000000000,''),
            (u'Acct Bytes', 'acct_bytes', 0,0,100000000000,''),
            (u'TCP Active', 'tcp_active', 1,0,10000000,''),
            (u'TCP Passive', 'tcp_passive', 1,0,10000000,''),
            (u'TCP Established', 'tcp_established', 1,0,10000000,''),
               ) ),
        ('Physical Interfaces',
            'snmp_interfaces','', True, True,
            u'SNMP Interface', '', '',
            'AVERAGE',103680, True, False, '.',(
            ('IP Address','address', True, True, True, True, False, False,'',''),
            ('IP Mask','mask',False, True, True, True, False,'','',''),
            ('Peer Address','peer',False, True, True, True, False,'','',''),
            ('Speed','speed',False, True, True, True, False,1,'',''),
            ('Percentile','percentile',False, True, False, True, False,'','',''),
            ('Flip In Out in Graphs','flipinout',False, True, True, True, False,0,'',''),
            ('Pings to Send','pings',False, True, True, True, False,50,'',''),
            ('Fixed Admin Status','fixed_admin_status',False, True, True, True, False,0,'','')
            ), (
            (u'Input Bytes', 'input', 1,0,0,'speed'),
            (u'Output Bytes', 'output', 1,0,0,'speed'),
            (u'Input Errors', 'inputerrors', 1,0,0,'speed'),
            (u'Output Errors', 'outputerrors', 1,0,0,'speed'),
            (u'Round Trip Time', 'rtt', 0,0,10000,''),
            (u'Packet Loss', 'packetloss', 0,0,1000,''),
            (u'Input Packets', 'inpackets', 1,0,0,'speed'),
            (u'Output Packets', 'outpackets', 1,0,0,'speed'),
            (u'Drops', 'drops', 1,0,0,'speed'),
                ) ),

        ('BGP Neighbors',
                'bgp_peers','', True, True,
                u'BGP Neighbor', '' , '',
                'AVERAGE',103680, False, False, '.',(
            ('Local IP','local',True, True, True, False, True, False,'',''),
            ('Remote IP','remote', False, True, True, False, False ,False,'',''),
            ('Autonomous System','asn',True, True, True, False, True, False,'',''),
            ), (
            (u'BGP In Updates', 'bgpin', 1,0,10000000,''),
            (u'BGP Out Updates', 'bgpout', 1,0,10000000,''),
            (u'BGP Uptime', 'bgpuptime', 0,0,10000000,''),
            (u'Accepted Routes', 'accepted_routes', 0,0,9000000,''),
            (u'Advertised Routes', 'advertised_routes', 0,0,9000000,''),
                ) ),
        (u'Storage',
                'storage','', True, True,
                u'Storage Device', '', '',
                'AVERAGE',103680, False, False, '.',(
            ('Disk Type','storage_type', True, True, True, False, False, False,'',''),
            ('Size (bytes)','size', True, True, True, True, False, False,'',''),
            ('Usage Threshold','usage_threshold',False, True, False, True, False,80,'',''),
            ), (
            (u'Storage Block Size', 'storage_block_size', 0,0,0,'size'),
            (u'Storage Block Count', 'storage_block_count', 0,0,0,'size'),
            (u'Storage Used Blocks', 'storage_used_blocks', 0,0,0,'size'),
                ) ),
        (u'Solaris System Info',
                'host_information','solaris,sparc,sun,11.2.3.10,8072.3.2.3', True, True,
                u'Solaris Host', '', '',
                'AVERAGE',103680, False, False, '.',(
            (u'Number of Processes','cpu_num', False, True, True, False, True, '','',''),
            (u'System Name','name',True, True, True, False, True, '','',''),
            (u'Location','location',True, True, True, False, True, '','',''),
            (u'Contact','contact',True, True, True, False, True, '','',''),
            ), (
            (u'CPU User Ticks', 'cpu_user_ticks', 1,0,86400,''),
            (u'CPU Idle Ticks', 'cpu_idle_ticks', 1,0,86400,''),
            (u'CPU Wait Ticks', 'cpu_wait_ticks', 1,0,86400,''),
            (u'CPU Kernel Ticks', 'cpu_kernel_ticks', 1,0,86400,''),
            (u'Swap Total', 'swap_total', 0,0,10000000000,''),
            (u'Swap Available', 'swap_available', 0,0,10000000000,''),
            (u'Mem Total', 'mem_total', 0,0,10000000000,''),
            (u'Mem Available', 'mem_available', 0,0,10000000000,''),
            (u'Load Average 1', 'load_average_1', 0,0,1000,''),
            (u'Load Average 5', 'load_average_5', 0,0,1000,''),
            (u'Load Average 15', 'load_average_15', 0,0,1000,''),
                ) ),
        (u'Linux/Unix System Info',
                'host_information','2021.250.10,linux,2021.250.255,freebsd,netSnmp,8072', True, True,
                u'Linux/Unix Host', '', '',
                'AVERAGE',103680, False, False,'.',(
            (u'Number of Processes','cpu_num', False, True, True, False, True, '','',''),
            (u'CPU Usage Threshold','cpu_threshold', False, False, True, False, True,'80','',''),
            (u'System Name','name',True, True, True, False, True, '','',''),
            (u'Location','location',True, True, True, False, True, '','',''),
            (u'Contact','contact',True, True, True, False, True, '','',''),
            ), (
            (u'CPU User Ticks', 'cpu_user_ticks', 1,0,86400,''),
            (u'CPU Idle Ticks', 'cpu_idle_ticks', 1,0,86400,''),
            (u'CPU Nice Ticks', 'cpu_nice_ticks', 1,0,86400,''),
            (u'CPU System Ticks', 'cpu_system_ticks', 1,0,86400,''),
            (u'Load Average 1', 'load_average_1', 0,0,1000,''),
            (u'Load Average 5', 'load_average_5', 0,0,1000,''),
            (u'Load Average 15', 'load_average_15', 0,0,1000,''),
            (u'Num Users', 'num_users', 0,0,10000,''),
            (u'Num Procs', 'num_procs', 0,0,10000,''),
            (u'TCP Active', 'tcp_active', 1,0,10000,''),
            (u'TCP Passive', 'tcp_passive', 1,0,10000,''),
            (u'TCP Established', 'tcp_established', 1,0,10000,''),
                ) ),
        (u'Windows System Info',
                'host_information','enterprises.311', True, True,
                u'Windows Host', '', '', 
                'AVERAGE',103680, False, False,'.',(
            (u'Number of Processes','cpu_num', False, True, True, False, True, '1','',''),
            (u'CPU Usage Threshold','cpu_threshold', False, False, True, False, True,'80','',''),
            (u'System Name','name',True, True, True, False, True, '','',''),
            (u'Location','location',True, True, True, False, True, '','',''),
            (u'Contact','contact',True, True, True, False, True, '','',''),
            ), (
            (u'CPU', 'cpu', 0,0,100,''),
            (u'Num Users', 'num_users', 0,0,10000,''),
            (u'Num Procs', 'num_procs', 0,0,10000,''),
            (u'TCP Active', 'tcp_active', 1,0,10000,''),
            (u'TCP Passive', 'tcp_passive', 1,0,10000,''),
            (u'TCP Established', 'tcp_established', 1,0,10000,''),
                ) ),
        ('Applications',
                'hostmib_apps','', True, False,
                u'HostMIB Application', '', '',
                'AVERAGE',103680, False, False, '.',(
            (u'Instances at Discovery','instances',True, True, True, False, True, '','',''),
            (u'Ignore Case','ignore_case',True, True, True, False, True, '','',''),
            ), (
            (u'Current Instances', 'current_instances', 0,0,99999,''),
            (u'Used Memory', 'used_memory', 0,0,9999999,''),
                ) ),
        ('Cisco Power Supply',
                'cisco_envmib','PowerSupply,5.1.2,5.1.3', True, True,
                u'Cisco Power Supply','', '',
                'AVERAGE', 103680, True, False,'ent.9',(
            ), (
                ) ),
        ('Cisco Temperature',
                'cisco_envmib','Temperature,3.1.2,3.1.6', True, True,
                u'Cisco Temperature', '', '',
                'AVERAGE',103680, False, False,'ent.9',(
            ), (
            (u'Temperature', 'temperature', 0,0,100,''),
                ) ),
        ('Cisco Voltage',
                'cisco_envmib','Voltage,2.1.2,2.1.7', True, True,
                u'Cisco Voltage', '', '',
                'AVERAGE', 103680, False, False, 'ent.9',( ), ( ) ),
        ('Cisco SA Agent',
                'cisco_saagent', '', True, True,
                u'Cisco SA Agent', '', '',
                'AVERAGE',103680, False, False, 'ent.9',(
            ), (
            (u'Forward Jitter', 'forward_jitter', 0,0,100,''),
            (u'Backward Jitter', 'backward_jitter', 0,0,100,''),
            (u'RT Latency', 'rt_latency', 0,0,100,''),
            (u'Forward Packetloss', 'forward_packetloss', 0,0,100,''),
            (u'Backward Packetloss', 'backward_packetloss', 0,0,100,''),
                ) ),
        ('Reachable',
                'reachability','', True, True, 
                u'Reachability', '', '',
                'AVERAGE',103680, False, False,'',(
            (u'Pings to Send','pings',False, True, False, True, False,'','',''),
            (u'Loss Threshold%','threshold',False, True, False, True, False,'','',''),
            (u'Interval (ms)','interval',False, True, False, True, False,'','',''),
            ), (
            (u'RTT', 'rtt', 0,0,10000,''),
            (u'Packetloss', 'packetloss', 0,0,1000,''),
                ) ),
        ('NTP',
                'ntp_client','', False, True,
                u'NTP', '', '',
                'AVERAGE', 103680, False, False,'',(), () ),
        ('Compaq Physical Drives',
                'cpqmib','phydrv', False, True,
                u'Compaq Physical Drive', '', '',
                'AVERAGE', 103680, True, False, '.',(
            (u'Controller', 'controller', True, True, False, False, True, '','',''),
            (u'Drive', 'drvindex', True, True, False, False, True, '','',''),
            (u'Drive Model', 'drive', False, True, False, False, True, '','',''),
            ), (
                ) ),
        ('Compaq Fans',
                'cpqmib','fans', False, True,
                u'Compaq Fan', '', '',
                'AVERAGE', 103680, False, False, '.',(
            (u'Location', 'location', True, True, True, False, True, '','',''),
            (u'Chassis', 'chassis', False, True, True, False, True, '','',''),
            (u'Fan', 'fan_index', False, True, True, False, True, '','',''),
            ), (
                ) ),
        ('Compaq Temperature',
                'cpqmib','temperature', False, True,
                u'Compaq Temperature', '', '',
                'AVERAGE',103680, False, False, '.',(
            (u'Location', 'location', False, True, True, False, True,  '','',''),
            (u'Chassis', 'chassis', False, True, True, False, True,  '','',''),
            (u'Sensor', 'temp_index', False, True, True, False, True,  '','',''),
            ), (
            (u'Temperature', 'temperature', 0,0,1000,''),
                ) ),
        ('IIS Webserver Information',
                'snmp_simple','1.3.6.1.4.1.311.1.7.3.1.1.0|IIS Information', False, True,
                u'IIS Info', '', '',
                'AVERAGE', 103680, False, False,'ent.311',(
            ), (
            (u'Total Bytes Received', 'tbr', 1,0,100000000,''),
            (u'Total CGI Requests', 'tcgir', 1,0,100000000,''),
            (u'Total Files Sent', 'tfs', 1,0,100000000,''),
            (u'Total Gets', 'tg', 1,0,100000000,''),
            (u'Total Posts', 'tp', 1,0,100000000,''),
                ) ),
        ('Apache',
                'apache','', False, True,
                u'Apache' ,'', '',
                'AVERAGE', 103680, False, False, '', (
            ), (
            (u'Total Accesses', 'tac', 1,0,100000000,''),
            (u'Total kBytes', 'tkb', 1,0,100000000,''),
            (u'CPU Load', 'cplo', 0,0,1000,''),
            (u'Uptime', 'up', 0,0,10000000,''),
            (u'Bytes Per Request', 'bpr', 0,0,10000000,''),
            (u'Busy Workers', 'bw', 0,0,1000,''),
            (u'Idle Workers', 'iw', 0,0,1000,''),
                ) ),
        ('APC',
                'apc','', True, True,
                u'APC', '', '',
                'AVERAGE', 103680, False, False, 'ent.318',(
            ), (
            (u'Battery Capacity', 'capacity', 0,0,100,''),
            (u'Output Load', 'load', 0,0,100,''),
            (u'Input Voltage', 'in_voltage', 0,0,400,''),
            (u'Output Voltage', 'out_voltage', 0,0,400,''),
            (u'Time Remaining', 'time_remaining', 0,0,100000000,''),
            (u'Temperature', 'temperature', 0,0,200,''),
                ) ),
        ('Alteon Real Server',
                'alteon_realservers','', True, True,
                u'Alteon Real Server', '', '',
                'AVERAGE', 103680, False, False, 'ent.1872',(
            (u'Hostname', 'hostname', True, True, True, True, False,  '','',''),
            (u'Max Connections', 'max_connections', False, True, True, True, False,  '','',''),
            ), (
            (u'Total Sessions', 'total_sessions', 1,0,100000000,''),
            (u'Current Sessions', 'current_sessions', 0,0,0,'max_connections'),
            (u'Failures', 'failures', 1,0,10000,''),
            (u'Octets', 'octets', 1,0,100000000,''),
                ) ),
        ('Alteon Virtual Server',
                'alteon_virtualservers','', False, True,
                u'Alteon Virtual Server', '', '',
                'AVERAGE', 103680, False, False, 'ent.1872',(
            (u'Hostname', 'hostname', True, True, True, True, False,  '','',''),
            ), (
            (u'Total Sessions', 'total_sessions', 1,0,100000000,''),
            (u'Current Sessions', 'current_sessions', 0,0,20000,''),
            (u'Octets', 'octets', 1,0,100000000,''),
                ) ),
        ('Alteon Real Services',
                'alteon_realservices','', False, True,
                u'Alteon Real Services', '', '',
                'AVERAGE', 103680, False, False, 'ent.1872',(
            (u'Hostname', 'hostname', True, True, True, True, False,  '','',''),
            (u'Address', 'address', True, True, True, True, False,  '','',''),
            (u'Port', 'port', True, True, True, True, False,  '','',''),
            (u'Real Server', 'real_server', False, False, True, False, True,  '','',''),
            ), (
            (u'Response Time', 'response_time', 0,0,10000,''),
                ) ),
        ('Alteon System Info',
                'host_information','enterprises.1872', True, True,
                u'Alteon System Info', '', '',
                'AVERAGE', 103680, False, False, 'ent.1872',(
            (u'System Name','name',True, True, True, False, True, False,'',''),
            (u'Location','location',True, True, True, False, True, False,'',''),
            (u'Contact','contact',True, True, True, False, True, False,'',''),
            (u'Number of CPUs','cpu_num',False, False, True, False, False, False,'',''),
            ), (
            (u'TCP Active', 'tcp_active', 1,0,10000,''),
            (u'TCP Passive', 'tcp_passive', 1,0,10000,''),
            (u'TCP Established', 'tcp_established', 1,0,10000,''),
            (u'Memory Total', 'mem_total', 0,0,10000000000,''),
            (u'Memory Used', 'mem_used', 0,0,10000000000,''),
            (u'CPU A 1 sec', 'cpua_1sec', 0,0,1000,''),
            (u'CPU A 4 sec', 'cpua_4sec', 0,0,1000,''),
            (u'CPU A 64 sec', 'cpua_64sec', 0,0,1000,''),
            (u'CPU B 1 sec', 'cpub_1sec', 0,0,1000,''),
            (u'CPU B 4 sec', 'cpub_4sec', 0,0,1000,''),
            (u'CPU B 64 sec', 'cpub_64sec', 0,0,1000,''),
                ) ),
        ('Brocade Sensors',
                'brocade_sensors','', False, False,
                u'Brocade Sensors', '', '',
                'AVERAGE', 103680, False, False, 'ent.1588',(
            (u'Type','sensor_type',False, True, True, False, False, False,'',''),
            ), (
            (u'Sensor Value', 'sensor_value', 0,0,30000000,''),
                ) ),
        ('Brocade FC Ports',
                'brocade_fcports','', False, False,
                u'Brocade FC Ports', '', '',
                'AVERAGE', 103680, False, False, 'ent.1588',(
            (u'Physical Status','phy', False, True, True, False, False, False,'',''),
            ), (
            (u'Tx Words', 'tx_words', 1,0,100000000,''),
            (u'Rx Words', 'rx_words', 1,0,100000000,''),
            (u'Tx Frames', 'rx_frames', 1,0,100000000,''),
            (u'Rx Words', 'rx_frames', 1,0,100000000,''),
                ) ),
        ('UPS',
                'ups','', True, True,
                u'UPS', '', '',
                'AVERAGE', 103680, False, False, '.',(
            (u'Identification','ident',False, True, True, False, True,'','',''),
            (u'UPS OID','ups_oid',False, True, True, False, True,'','',''),
            ), (
            (u'Battery Temperature', 'temperature', 0,0,200,''),
            (u'Minutes Remaining', 'minutes_remaining', 0,0,10000200,''),
            (u'Charge Remaining', 'charge_remaining', 0,0,10000200,''),
                ) ),
        ('UPS Input Line',
                'ups_lines','1.3.6.1.2.1.33.1|in|0', False, True,
                u'UPS Input Line', '', '',
                'AVERAGE', 103680, False, False, '.',(
            ), (
            (u'Voltage', 'voltage', 0,0,500,''),
            (u'Current', 'current', 0,0,500,''),
                ) ),
        ('UPS Output Line',
                'ups_lines','1.3.6.1.2.1.33.1|out|0', False, True,
                u'UPS Output Line', '', '',
                'AVERAGE', 103680, False, False, '.',(
            ), (
            (u'Voltage', 'voltage', 0,0,500,''),
            (u'Current', 'current', 0,0,500,''),
            (u'Load', 'load', 0,0,100,''),
                ) ),
        ('Mitsubishi UPS Input Line',
                'ups_lines','1.3.6.1.4.1.13891.101|in|1', False, True,
                u'Mitsubishi UPS Input Line', '', '',
                'AVERAGE', 103680, False, False, '.',(
            ), (
            (u'Voltage', 'voltage', 0,0,500,''),
            (u'Current', 'current', 0,0,500,''),
            (u'Power', 'power', 0,0,100000,''),
                ) ),
        ('Mitsubishi UPS Output Line',
                'ups_lines','1.3.6.1.4.1.13891.101|out|1', False, True,
                u'Mitsubishi UPS Output Line', '', '',
                'AVERAGE', 103680, False, False, '.',(
            ), (
            (u'Voltage', 'voltage', 0,0,500,''),
            (u'Current', 'current', 0,0,500,''),
            (u'Power', 'power', 0,0,100000,''),
            (u'Load', 'load', 0,0,100,''),
                ) ),
        ('Cisco PIX',
                'pix_connections','', True, True,
                u'PIX Connection Stat', '', '',
                'AVERAGE', 103680, False,  False,'ent.9',
                (), () ),
        ('Cisco NAT',
                'snmp_simple','.1.3.6.1.4.1.9.10.77.1.2.1.0|NAT', False, True,
                u'Cisco NAT', '', '',
                'AVERAGE',103680, False, False, 'ent.9',(), () ),
        ('Sensors',
                'sensors','', True, True,
                u'Sensors', '', '',
                'AVERAGE', 103680, False, False, '.',(
            (u'Table Index','table_index',False, False, False, False, True,'','',''),
            (u'Row Index','row_index',False, False, False, False, True,'','',''),
            (u'Units','units',False, True, False, True, False,'','',''),
            (u'Measure','measure',False, True, False, True, False,'','',''),
            (u'Multiplier','multiplier',False, True, False, True, False,'','',''),
            ), (
            (u'Value', 'value', 0,-100000,100000,''),
                ) ),
        ('OS/400 System Info',
                'snmp_simple','.1.3.6.1.4.1.2.6.4.5.1.0|OS400', True, True,
                u'OS/400 Host', '', '',
                'AVERAGE', 103680, False, False, '.',(), () ),
        ('Dell Chassis',
                'snmp_simple','.1.3.6.1.4.1.674.10892.1.200.10.1.2.1|Chassis status', True, True,
                u'Dell Chassis', '', '',
                'AVERAGE', 103680, False, False, '.',(), () ),
        ('Generic FC Ports',
                'fc_ports','', True, False,
                u'Fibre Channel Interface', '', '',
                'AVERAGE', 103680, False, False, '.',(), () ),
        ('Cisco 802.11X Device',
                'snmp_simple','.1.3.6.1.4.1.9.9.273.1.1.2.1.1.1|Cisco AP', False, True, 
                u'Cisco 802.11X Device', '', '',
                'AVERAGE', 103680, False, False, 'ent.9',(
            ), (
            (u'Associated', 'associated', 0,0,2100,''),
                )),
        ('Compaq Power Supply',
                'cpqmib','powersupply', False, True,
                u'Compaq Power Supply', '', '',
                'AVERAGE', 103680, False, False, '.',(), () ),
        )
    
config_transfers = (
        (u'No Configuration Transfer', u''),
        (u'Cisco IOS, > 12.0 (CONFIG-COPY-MIB)', u'cisco_cc'),
        (u'Cisco IOS, < 12.0 (SYS-MIB)', u'cisco_sys'),
        (u'Cisco CatOS (STACK-MIB)', u'cisco_catos'),
        (u'Alteon WebOS Switches (DANGEROUS)', u'alteon_webos'),
    )

event_types = (
        # display_name, severity, tag, text, gen_alm, alm_up, alm_dur, sh_host
    (u'Unknown', u'Warning', 'unknown', u'$attribute $state $info',False, 1, 0,  True),
    (u'Administrative', u'Administrative', 'admin', u'$attribute $info',True, 1, 1800, True),
    (u'SLA', u'Information', 'sla', u'$attribute $info (${client} ${description})',True, 1, 1800, True),
    (u'Internal', u'Information', 'internal', u'$user $attribute $state $info',False,1,0, False),

    (u'BGP Status', u'Critical', 'bgp_status', u'BGP Neighbor $attribute $state $info (${client} ${description})',True, 1, 0, True),
    (u'BGP Notification', u'Information', 'bgp_notify', u'Notification $state $attribute $info',False, 1, 0, True),

    (u'TCP/UDP Service', u'Service', 'tcpudp_service', u'TCP/UDP Service $attribute $state (${client} ${description}) $info',True, 1, 0, True),
    (u'TCP Content', u'Service', 'tcp_content', u'Content Response on $attribute is $state (${client} ${description}) $info',True, 1, 0, True),

    (u'Configuration', u'Warning', 'configuration', u'$user changed configuration from $source',False, 1, 0, True),
    (u'Interface Protocol', u'Fault', 'interface_protocol', u'Interface $attribute Protocol $state $info (${client} ${description})',True, 1, 0, True),
    (u'Interface Link', u'Big Fault', 'interface_link', u'Interface $attribute Link $state $info (${client} ${description})',False, 1, 0, True),
    (u'Controller Status', u'Big Fault', 'controller_status', u'Controller  $info $attribute $state',False, 1, 0, True),
    (u'Interface Shutdown', u'Big Fault', 'interface_shutdown', u'Interface $attribute $info $state (${client} ${description})',False, 4, 0, True),
    (u'Clear Counters', u'Information', 'clear_counters', u'<user> Cleared Counters of $attribute  (${client} ${description})',False, 1, 0, True),
    (u'Environmental', u'Critical', 'environment', u'$attribute $state $info',True, 1, 0, True),
    (u'Duplex Mismatch', u'Warning', 'duplex_mismatch', u'Duplex Mismatch, $attribute is not full duplex and <user> $info is full duplex',False, 1, 0, True),
    (u'ACL', u'Information', 'acl', u'ACL $attribute $state $info packets from <user>',False, 1, 0, True),
    (u'Excess Collisions', u'Warning', 'collision', u'Excess Collisions on Interface $attribute',False, 1, 0, True),
    (u'Application', u'Critical', 'application', u'Application $attribute is $state $info (${client} ${description})',True, 1, 0, True),
    (u'Reachability', u'Critical', 'reachability', u'Host is $state with $info',True, 1, 0, True),
    (u'NTP', u'Information', 'ntp', u'$attribute is $state $info',True, 1, 0, True),

    (u'APC Status', u'Critical', 'apc_status', u'$attribute is $state $info',True, 1, 0, True),

    (u'Alteon RServer', u'Fault', 'alteon_rserver', u'Real Server $attribute is $state',True, 1, 0, True),
    (u'Alteon Service', u'Fault', 'alteon_service', u'Real Service $attribute is $state $info',True, 1, 0, True),
    (u'Alteon VServer', u'Fault', 'alteon_vserver', u'Virtual Server $attribute is $state $info',False, 1, 0, True),

    (u'Brocade FC Port', u'Fault', 'brocade_fcport', u'$attribute $state ($info)',True, 1, 0, True),

    (u'OS/400 Error', u'Critical', 'os400_error', u'A subsystem is $state on the OS/400',True, 1, 0, True),
    (u'Storage Controller', u'Big Fault', 'storage_controller', u'$info',True, 1, 0, True)
    )

event_severities = [
    [u'Unknown', 127, '000000', 'ffffff'],
    [u'Warning', 30, '00aa00', 'ffffff'],
    [u'Fault', 40, 'f51d30', 'eeeeee'],
    [u'Big Fault', 50, 'da4725','ffffff'],
    [u'Critical',60, 'ff0000', 'ffffff'],
    [u'Administrative',10, '8d00ba', 'ffffff'],
    [u'Information',20, 'f9fd5f', '000000'],
    [u'Service',35, '0090f0', 'ffffff']
    ]

logfiles = [
    [u'Database', u''],
    [u'Messages', u'/var/log/messages'],
    ]

logmatch_default_rows = [
        #text,start,host,attr,state,event_id,[fields]
        [u'%BGP-5-ADJCHANGE: neighbour (\S+) (\S+)$',
            False,None,1,2,'bgp_status',[]],
        [u'%BGP-3-NOTIFICATION: (\S+ \S+) neighbor (\S+) \S+ (\S+ \S+ \S+) \S+ \S+',
            False,None,2,1,'bgp_notify',[['info',3]]],
        [u'%CDP-4-DUPLEX_MISMATCH: duplex mismatch discovered on (\S+)',
            False,None,1,None,'duplex_mismatch',[]],
        [u'%CLEAR-5-COUNTERS: Clear counter on \S+ (\S+) by (\S+)',
            False,None,1,None,'clear_counters',[['user',2,]]],

        [u'%CONTROLLER-5-UPDOWN: Controller \S+ (\S+), changed state to (\S+) \([^)]+\)$',
            False,None,1,2,'controller_status',[['info',3]]],
        [u'%LINK-3-UPDOWN: Interface (\S+), changed state to (\S+)',
            False,None,1,2,'interface_link',[]],
        [u'%LINK-5-CHANGED: Interface (\S+), changed state to (\S+)',
            False,None,1,2,'interface_shutdown',[]],
        [u'%LINEPROTO-5-UPDOWN: Line protocol on Interface (\S+), changed state to (\S+)',
            False,None,1,2,'interface_protocol',[]],
        [u'%SYS-5-CONFIG_I: Configured from \S+ by (\S+) on \S+ \((\S+)\)',
            False,None,None,None,'configuration',[['user',1],['source',2]]],

        [u'%SYS-5-(?:RESTART|RELOAD): (.+)$',
            False,None,None,None,'environment',[['info',1]]],
        [u'%SEC-6-IPACCESSLOG(?:DP|P|NP|S): list (.+)$',
            False,None,None,None,'acl',[['info',1]]],
        [u'EXCESSCOLL: (\S+)',
            False,None,1,None,'collision',[]],
        [u'WebOS <slb>: No services are available for Virtual Server\d+:(\S+)',
            False,None,1,'down','alteon_vserver',[]],
        [u'UPS: ([^.]+)\. (.+)$',
            False,None,'UPS',None,'environment',[['info',1]]],
        [u'WebOS <slb>: real server (\S+) operational',
            False,None,1,'up','alteon_rserver',[]],
        [u'WebOS <slb>: cannot contact real server (\S+)',
            False,None,1,'down','alteon_rserver',[]],
        [u'WebOS <slb>: Services are available for Virtual Server\d+:(\S+)',
            False,None,1,'up','alteon_vserver',[]],
        [u'WebOS <slb>: real service (\S+) operational',
            False,None,1,'up','alteon_service',[]],
        [u'WebOS <slb>: cannot contact real service (\S+)',
            False,None,1,'down','alteon_service',[]],

    ]

# name, text, thres, atype, rows
#   expression, oper, limit, show_res, show_info,show_expr
slas = (
        (u'Cisco Router', u'Router:', u'Cisco System Info', (
            ('$cpu - $cpu_threshold', '>', 0, True, u'Usage > $cpu_threshold', u'$cpu', u'%'),
            ('$mem_used * 100 / ($mem_used + $mem_free)', '>', 80, True, u'Memory Usage > 80%', u'$mem_used * 100 / ($mem_used + $mem_free)', u'%'),
            ('OR','=',0, False, u'', u'', u''),
            )),
        (u'Linux/Unix CPU', u'', u'Linux/Unix System Info', (
            ('$load_average_5', '>', 5, True, u'Load Average > 5', u'$load_average_5', u''),
            ('($cpu_user_ticks + $cpu_nice_ticks + $cpu_system_ticks) * 100 / ($cpu_user_ticks + $cpu_idle_ticks + $cpu_nice_ticks + $cpu_system_ticks) - $cpu_threshold', '>', 0, True, u'Usage > $cpu_threshold%', u'($cpu_user_ticks + $cpu_nice_ticks + $cpu_system_ticks) * 100 / ($cpu_user_ticks + $cpu_idle_ticks + $cpu_nice_ticks + $cpu_system_ticks)', u'%'),
            ('OR','=',0, False, u'', u'', u''),
            )),
        (u'Windows CPU', u'', u'Windows System Info', (
            ('$cpu', '>', 90, True, u'CPU > 90%', u'$cpu', u'%'),
            ('$num_procs - $proc_threshold', '>', 0, True, u'Processes > $proc_threshold', u'$num_procs', u'Processes'),
            ('OR','=',0, False, u'', u'', u''),
            )),
        (u'Physical Interface', u'Interface:', u'Physical Interfaces', (
            ('$in * 100 / $speed', '>', 90, True, u'IN > 90%', u'$in / 1000', u'kbps'),
            ('$out * 100 / $speed', '>', 90, True, u'IN > 90%', u'$out / 1000', u'kbps'),
            ('($inerrors * 100) / ($inpackets + 1 )', '>', 10, True, u'IN ERR > 20%', u'($inerrors * 100) / ($inpackets + 1)', u'% = $inerrors Eps'),
            )),
        (u'Storage', u'Storage:', u'Storage', (
            ('($storage_used_blocks * 100) / $storage_block_count - $usage_threshold', '>', 0, True, u'Used > $usage_threshold', u'($storage_used_blocks * 100) / $storage_block_count', u'%'),
            )),
        )
pollers = [
        ['no_poller','No Polling','no_poller',''],

        ['input','SNMP Input Rate','snmp_counter','1.3.6.1.2.1.31.1.1.1.6.${index}|1.3.6.1.2.1.2.2.1.10.${index}'],
        ['verify_interface_number','SNMP Verify Interface Number','verify_interface_number',''],
        ['cisco_snmp_ping_start','Cisco SNMP Ping Start','cisco_snmp_ping_start',''],
        ['cisco_snmp_ping_wait','Cisco SNMP Ping Wait','cisco_snmp_ping_wait',''],
        ['packetloss','Cisco SNMP Ping Get PL','cisco_snmp_ping_get_pl',''],
        ['rtt','Cisco SNMP Ping Get RTT','cisco_snmp_ping_get_rtt',''],
        ['cisco_snmp_ping_end','Cisco SNMP Ping End','cisco_snmp_ping_end',''],
        ['output','SNMP Output Rate','snmp_counter','1.3.6.1.2.1.31.1.1.1.10.${index}|1.3.6.1.2.1.2.2.1.16.${index}'],
        ['outputerrors','SNMP Output Errors','snmp_counter','1.3.6.1.2.1.2.2.1.20.${index}'],
        ['inputerrors','SNMP Input Errors','snmp_counter','1.3.6.1.2.1.2.2.1.14.${index}'],
        ['ifOper','SNMP Interface Operational Status','snmp_status','1.3.6.1.2.1.2.2.1.8.${index}|1=up,2=down,3=testing,4=unknown|down'],
        ['ifAdmin','SNMP Interface Administrative Status','snmp_status','1.3.6.1.2.1.2.2.1.7.${index}|1=up,2=down,3=testing,4=unknown|down'],
        ['cpu','Cisco CPU Utilization','snmp_counter','1.3.6.1.4.1.9.9.109.1.1.1.1.5.1'],
        ['inpackets','SNMP Input Packets','snmp_counter','1.3.6.1.2.1.31.1.1.1.7.${index}|1.3.6.1.2.1.2.2.1.11.${index}'],
        ['outpackets','SNMP Output Packets','snmp_counter','1.3.6.1.2.1.31.1.1.1.11.${index}|1.3.6.1.2.1.2.2.1.17.${index}'],
        ['tcp_status,tcp_content,conn_delay','TCP Port Check & Delay','tcp_status',''],
        ['mem_used','Cisco Used Memory','snmp_counter','1.3.6.1.4.1.9.9.48.1.1.1.5.1'],
        ['mem_free','Cisco Free Memory','snmp_counter','1.3.6.1.4.1.9.9.48.1.1.1.6.1'],
        ['drops','SNMP Drops','snmp_counter','1.3.6.1.2.1.2.2.1.19.${index}'],
        ['cpu','Cisco 2500 Series CPU Utilization','snmp_counter','1.3.6.1.4.1.9.2.1.56.0'],
        ['bgpin','BGP Inbound Updates','snmp_counter','1.3.6.1.2.1.15.3.1.10.${remote}'],
        ['bgpout','BGP Outbound Updates','snmp_counter','1.3.6.1.2.1.15.3.1.11.${remote}'],
        ['bgpuptime','BGP Uptime','snmp_counter','1.3.6.1.2.1.15.3.1.16.${remote}'],
        ['storage_used_blocks','Storage Device Used Blocks','snmp_counter','1.3.6.1.2.1.25.2.3.1.6.${index}'],
        ['storage_block_count','Storage Device Total Blocks','snmp_counter','1.3.6.1.2.1.25.2.3.1.5.${index}'],
        ['storage_block_size','Storage Device Block Size','snmp_counter','1.3.6.1.2.1.25.2.3.1.4.${index}'],
        ['bgp_peer_status','BGP Peer Status','snmp_status','1.3.6.1.2.1.15.3.1.2.${remote}|6=up|down'],
        ['cpu_kernel_ticks','CPU Kernel Time','snmp_counter','1.3.6.1.4.1.2021.11.55.0'],
        ['cpu_idle_ticks','CPU Idle Time','snmp_counter','1.3.6.1.4.1.2021.11.53.0'],
        ['cpu_wait_ticks','CPU Wait Time','snmp_counter','1.3.6.1.4.1.2021.11.54.0'],
        ['cpu_system_ticks','CPU System Time','snmp_counter','1.3.6.1.4.1.2021.11.52.0'],
        ['mem_available','Real Memory Available','snmp_counter','1.3.6.1.4.1.2021.4.6.0'],
        ['mem_total','Real Memory Total','snmp_counter','1.3.6.1.4.1.2021.4.5.0'],
        ['swap_available','Swap Memory Available','snmp_counter','1.3.6.1.4.1.2021.4.4.0'],
        ['swap_total','Swap Memory Total','snmp_counter','1.3.6.1.4.1.2021.4.3.0'],
        ['load_average_15','Load Average 15 min','snmp_counter','1.3.6.1.4.1.2021.10.1.3.3'],
        ['load_average_5','Load Average 5 min','snmp_counter','1.3.6.1.4.1.2021.10.1.3.2'],
        ['load_average_1','Load Average 1 min','snmp_counter','1.3.6.1.4.1.2021.10.1.3.1'],
        ['cpu_user_ticks','CPU User Time','snmp_counter','1.3.6.1.4.1.2021.11.50.0'],
        ['cpu_nice_ticks','CPU Nice Time','snmp_counter','1.3.6.1.4.1.2021.11.51.0'],
        ['tcp_established','TCP MIB Established','snmp_tcp_established',''],
        ['cpu','Host MIB Proc Average Util','snmp_walk_average','1.3.6.1.2.1.25.3.3.1.2'],
        ['num_procs','Host MIB Number of Processes','snmp_counter','1.3.6.1.2.1.25.1.6.0'],
        ['num_users','Host MIB Number of Users','snmp_counter','1.3.6.1.2.1.25.1.5.0'],
        ['tcp_active','TCP MIB Active Opens','snmp_counter','1.3.6.1.2.1.6.5.0'],
        ['tcp_passive','TCP MIB Passive Opens','snmp_counter','1.3.6.1.2.1.6.6.0'],
        ['tcp_established','TCP MIB Established Connections','snmp_counter','1.3.6.1.2.1.6.9.0'],
        ['app_status,current_instances,pids','Host MIB Process Verifier','hostmib_apps','${attribute}'],
        ['cisco_powersupply_status','Cisco Power Supply Status','snmp_status','1.3.6.1.4.1.9.9.13.1.5.1.3.${index}|1=up|down'],
        ['cisco_temperature_status','Cisco Temperature Status','snmp_status','1.3.6.1.4.1.9.9.13.1.3.1.6.${index}|1=up|down'],
        ['cisco_voltage_status','Cisco Voltage Status','snmp_status','1.3.6.1.4.1.9.9.13.1.2.1.7.${index}|1=up|down'],
        ['temperature','Cisco Temperature','snmp_counter','1.3.6.1.4.1.9.9.13.1.3.1.3.${index}'],
        ['sa_agent_verify','Verify SA Agent Operation','cisco_saagent_verify',''],
        ['forward_jitter','SA Agent Forward Jitter','cisco_saagent','${index}|fwd_jitter'],
        ['backward_jitter','SA Agent Backward Jitter','cisco_saagent','${index}|bwd_jitter'],
        ['rt_latency,forward_packetloss,backward_packetloss','SA Agent Packetloss','cisco_saagent','${index}|packetloss'],
        ['tcp_content_analisis','TCP Content Check','tcp_content',''],
        ['rtt,pl','Reachability Ping','reach_ping',''],
        ['status','Reachability Status','reach_status',''],
        ['','TCP Port Status','buffer','tcp_status'],
        ['','Host MIB Status','buffer','app_status'],
        ['ntp_status','NTP Status','ntp_client',''],
        ['used_memory','Host MIB Process Memory Usage','hostmib_perf','2'],
        ['temperature','Compaq Temperature','snmp_counter','1.3.6.1.4.1.232.6.2.6.8.1.4.${chassis}.${tempindex}'],
        ['temp_status','Compaq Temperature Status','snmp_status','1.3.6.1.4.1.232.6.2.6.8.1.6.${chassis}.${tempindex}|2=up|down'],
        ['fan_status','Compaq Fan Condition','snmp_status','1.3.6.1.4.1.232.6.2.6.7.1.9.${chassis}.${fanindex}|2=up|down'],
        ['compaq_disk','Compaq Drive Condition','snmp_status','1.3.6.1.4.1.232.3.2.5.1.1.6.${controller}.${drvindex}|2=up|down'],
        ['tbr','IIS Total Bytes Received','snmp_counter','1.3.6.1.4.1.311.1.7.3.1.4.0'],
        ['tcgir','IIS Total CGI Requests','snmp_counter','1.3.6.1.4.1.311.1.7.3.1.35.0'],
        ['tfs','IIS Total Files Sent','snmp_counter','1.3.6.1.4.1.311.1.7.3.1.5.0'],
        ['tg','IIS Total GETs','snmp_counter','1.3.6.1.4.1.311.1.7.3.1.18.0'],
        ['tp','IIS Total Posts','snmp_counter','1.3.6.1.4.1.311.1.7.3.1.19.0'],
        ['tac,tkb,cplo,up,bpr,bw,iw','Apache Status','apache',''],
        ['capacity','APC Battery Capacity','snmp_counter','1.3.6.1.4.1.318.1.1.1.2.2.1.0'],
        ['load','APC Output Load','snmp_counter','1.3.6.1.4.1.318.1.1.1.4.2.3.0'],
        ['in_voltage','APC Input Voltage','snmp_counter','1.3.6.1.4.1.318.1.1.1.3.2.1.0'],
        ['out_voltage','APC Output Voltage','snmp_counter','1.3.6.1.4.1.318.1.1.1.4.2.1.0'],
        ['time_remaining','APC Time Remaining','snmp_counter','1.3.6.1.4.1.318.1.1.1.2.2.3.0'],
        ['status','APC Battery Status','snmp_status','1.3.6.1.4.1.318.1.1.1.2.1.1.0|2=battery normal,3=battery low|battery unknown'],
        ['temperature','APC Temperature','snmp_counter','1.3.6.1.4.1.318.1.1.1.2.2.2.0'],
        ['output_status','APC Output Status','snmp_status','1.3.6.1.4.1.318.1.1.1.4.1.1.0|2=on line,3=on battery'],
        ['admin_state','Alteon RServer Admin','snmp_counter','1.3.6.1.4.1.1872.2.1.5.2.1.10.${index}'],
        ['oper_state','Alteon RServer Oper','snmp_status','1.3.6.1.4.1.1872.2.1.9.2.2.1.7.${index}|2=up|down'],
        ['current_sessions','Alteon RServer Current Sessions','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.5.1.2.${index}'],
        ['failures','Alteon RServer Failures','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.5.1.4.${index}'],
        ['octets','Alteon RServer Octets','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.5.1.7.${index}'],
        ['total_sessions','Alteon RServer Total Sessions','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.5.1.3.${index}'],
        ['admin_state','Alteon VServer Admin State','snmp_counter','1.3.6.1.4.1.1872.2.1.5.5.1.4.${index}'],
        ['current_sessions','Alteon VServer Current Sessions','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.7.1.2.${index}'],
        ['total_sessions','Alteon VServer Total Sessions','snmp_counter','1.3.6.1.4.1.1872.2.1.8.2.7.1.3.${index}'],
        ['octets','Alteon VServer Octets','snmp_counter','.1.3.6.1.4.1.1872.2.1.8.2.7.1.6.${index}'],
        ['admin_state','Alteon RService Admin State','snmp_counter','1.3.6.1.4.1.1872.2.1.5.2.1.10.${real_server}'],
        ['oper_state','Alteon RService Oper State','snmp_status','1.3.6.1.4.1.1872.2.1.9.2.4.1.6.${index}|2=up|down'],
        ['response_time','Alteon RService Response Time','snmp_counter','1.3.6.1.4.1.1872.2.1.9.2.4.1.7.${index}'],
        ['cpua_1sec','Alteon CPU A 1Sec','snmp_counter','1.3.6.1.4.1.1872.2.1.8.16.1.0'],
        ['cpua_4secs','Alteon CPU A 4Secs','snmp_counter','1.3.6.1.4.1.1872.2.1.8.16.3.0'],
        ['cpua_64secs','Alteon CPU A 64Secs','snmp_counter','1.3.6.1.4.1.1872.2.1.8.16.5.0'],
        ['cpub_1sec','Alteon CPU B 1Sec','snmp_counter','1.3.6.1.4.1.1872.2.1.8.1.16.2.0'],
        ['cpub_4secs','Alteon CPU B 4Secs','snmp_counter','1.3.6.1.4.1.1872.2.1.8.16.4.0'],
        ['cpub_64secs','Alteon CPU B 64Secs','snmp_counter','1.3.6.1.4.1.1872.2.1.8.16.6.0'],
        ['mem_total','Alteon Memory Total','snmp_counter','1.3.6.1.4.1.1872.2.1.8.12.6.0'],
        ['mem_used','Alteon Memory Used','snmp_counter','1.3.6.1.4.1.1872.2.1.8.12.4.0'],
        ['sensor_value','Brocade Sensor Value','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.1.22.1.4.${index}'],
        ['oper_status','Brocade Sensor Oper','snmp_status','1.3.6.1.4.1.1588.2.1.1.1.1.22.1.3.${index}|4=ok,3=alert,5=alert'],
        ['tx_words','Brocade FC Port TxWords','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.11.${index}'],
        ['rx_words','Brocade FC Port RxWords','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.12.${index}'],
        ['tx_frames','Brocade FC Port TxFrames','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.13.${index}'],
        ['rx_frames','Brocade FC Port RxFrames','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.14.${index}'],
        ['admin_state','Brocade FC Port Admin State','snmp_counter','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.5.${index}'],
        ['oper_status','Brocade FC Port Oper Status','snmp_status','1.3.6.1.4.1.1588.2.1.1.1.6.2.1.4.${index}|1=up,3=testing'],
        ['phy_state','Brocade FC Port Phy State','brocade_fcport_phystate','${index}'],
        ['status','UPS Battery Status','snmp_status','${ups_oid}.2.1.0|2=battery normal,1=battery unknown,3=battery low,3=battery depleted'],
        ['temperature','UPS Battery Temperature','snmp_counter','${ups_oid}.2.7.0'],
        ['minutes_remaining','UPS Battery Minutes Remaining','snmp_counter','${ups_oid}.2.3.0'],
        ['charge_remaining','UPS Battery Charge Remaining','snmp_counter','${ups_oid}.2.4.0'],
        ['voltage','UPS Input Voltage','snmp_counter','1.3.6.1.2.1.33.1.3.3.1.3.${index}'],
        ['current','UPS Input Current','snmp_counter','1.3.6.1.2.1.33.1.3.3.1.4.${index}'],
        ['voltage','UPS Output Voltage','snmp_counter','1.3.6.1.2.1.33.1.4.4.1.2.${index}'],
        ['current','UPS Output Current','snmp_counter','1.3.6.1.2.1.33.1.4.4.1.3.${index}'],
        ['load','UPS Output Load','snmp_counter','1.3.6.1.2.1.33.1.4.4.1.5.${index}'],
        ['voltage','Mitsu UPS Input Voltage','snmp_counter_mul','1.3.6.1.4.1.13891.101.3.3.1.3.${index}|0.1'],
        ['current','Mitsu UPS Input Current','snmp_counter_mul','1.3.6.1.4.1.13891.101.3.3.1.4.${index}|0.1'],
        ['power','Mitsu UPS Input Power','snmp_counter','1.3.6.1.4.1.13891.101.3.3.1.5.${index}'],
        ['voltage','Mitsu UPS Output Voltage','snmp_counter_mul','1.3.6.1.4.1.13891.101.4.4.1.2.${index}|0.1'],
        ['current','Mitsu UPS Output Current','snmp_counter_mul','1.3.6.1.4.1.13891.101.4.4.1.3.${index}|0.1'],
        ['power','Mitsu UPS Output Power','snmp_counter','1.3.6.1.4.1.13891.101.4.4.1.4.${index}'],
        ['load','Mitsu UPS Output Load','snmp_counter','1.3.6.1.4.1.13891.101.4.4.1.5.${index}'],
        ['accepted_routes','BGP Accepted Routes','snmp_counter','1.3.6.1.4.1.9.9.187.1.2.4.1.1.${remote}.1.1'],
        ['advertised_routes','BGP Advertised Routes','snmp_counter','1.3.6.1.4.1.9.9.187.1.2.4.1.6.${remote}.1.1'],
        ['pix_connections','Pix Connections Poller','snmp_counter','1.3.6.1.4.1.9.9.147.1.2.2.2.1.5.${index}'],
        ['cisco_nat_other_ip_inbound','Cisco NAT Other IP Inbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.2.1'],
        ['cisco_nat_icmp_inbound','Cisco NAT ICMP Inbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.2.2'],
        ['cisco_nat_udp_inbound','Cisco NAT UDP Inbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.2.3'],
        ['cisco_nat_tcp_inbound','Cisco NAT TCP Inbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.2.4'],
        ['cisco_nat_other_ip_outbound','Cisco NAT Other IP Outbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.3.1'],
        ['cisco_nat_icmp_outbound','Cisco NAT ICMP Outbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.3.2'],
        ['cisco_nat_udp_outbound','Cisco NAT UDP Outbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.3.3'],
        ['cisco_nat_tcp_outbound','Cisco NAT TCP Outbound','snmp_counter','1.3.6.1.4.1.9.10.77.1.3.1.1.3.4'],
        ['cisco_nat_active_binds','Cisco NAT Active Binds','snmp_counter','1.3.6.1.4.1.9.10.77.1.2.1.0'],
        ['sensor_verify','Verify Sensor Index','verify_sensor_index',''],
        ['value','Sensor Value','snmp_counter','1.3.6.1.4.1.2021.13.16.${table_index}.1.3.${row_index}'],
        ['storage_verify','Verify Storage Index','verify_storage_index',''],
        ['cpu400','OS 400 System Load','snmp_counter','1.3.6.1.4.1.2.6.4.5.1.0'],
        ['dell_om_chassis','Dell OpenManage Chassis','snmp_status','1.3.6.1.4.1.674.10892.1.200.10.1.2.1|1=other,2=unknown,3=ok,4=noncritical,5=critical,6=nonrecoverabl|unknown'],
        ['dell_om_temp','Dell OpenManage Ambient Temp','snmp_counter','1.3.6.1.4.1.674.10892.1.700.20.1.6.1.1'],
        ['dell_om_fan_1','Dell OpenManage Fan RPM #1','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.1'],
        ['dell_om_fan_2','Dell OpenManage Fan RPM #2','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.2'],
        ['dell_om_fan_3','Dell OpenManage Fan RPM #3','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.3'],
        ['dell_om_fan_4','Dell OpenManage Fan RPM #4','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.4'],
        ['dell_om_fan_5','Dell OpenManage Fan RPM #5','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.5'],
        ['dell_om_fan_6','Dell OpenManage Fan RPM #6','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.6'],
        ['dell_om_fan_7','Dell OpenManage Fan RPM #7','snmp_counter','1.3.6.1.4.1.674.10892.1.700.12.1.6.1.7'],
        ['status','FC Oper Status','snmp_status','1.3.6.1.2.1.75.1.2.2.1.2.${index}|1=up,2=offline,4=linkFailure'],
        ['rx_frames','FCPort RxFrames','snmp_counter','1.3.6.1.2.1.75.1.4.3.1.1.${index}'],
        ['tx_frames','FCPort TxFrames','snmp_counter','1.3.6.1.2.1.75.1.4.3.1.2.${index}'],
        ['associated','802.11x Associated Clients','snmp_counter','1.3.6.1.4.1.9.9.273.1.1.2.1.1.1'],
        ['power_status','Compaq Power Condition','snmp_status','1.3.6.1.4.1.232.6.2.9.3.1.4.${chassis}.${bayindex}|2=up'],
        ['cur_disk_q','Inf-64 Disk CurrentDiskQueue','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.16.${index}'],
        ['avg_disk_q','Inf-64 Disk AvgDiskQueu','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.10.${index}'],
        ['avg_disk_rdq','Inf-64 Disk avg Read DiskQueue','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.11.${index}'],
        ['avg_disk_wrq','Inf-64 Disk avg Write DiskQueue','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.12.${index}'],
        ['inf_d_read_time','Inf-64 Disk Read Time','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.2.${index}'],
        ['inf_d_write_time','Inf-64 Disk Write Time','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.4.${index}'],
        ['rd_ops','Inf-64 Disk Read rate','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.19.${index}'],
        ['wr_ops','Inf-64 Disk Write rate','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.22.${index}'],
        ['inf_d_read_rate','Inf-64 Disk Read Bytes','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.18.${index}'],
        ['inf_d_write_rate','Inf-64 Disk Write Bytes','snmp_counter','1.3.6.1.4.1.9600.1.2.44.1.21.${index}'],
        ]

backends = [
        [u'No Backend','',''],
        [u'Unknown Event','event_always','unknown'],
        [u'Alarm APC','event','apc_status'],
        [u'Alarm BGP Peer','event','bgp_status,,180'],
        [u'Alarm Brocade FC Port','event','brocade_fcport'],
        [u'Alarm Environmental','event','environment'],
        [u'Alarm NTP','event','ntp,nothing'],
        [u'Set Admin Status','admin_status','down=2|up=1,0'],
        [u'Alarm TCP Content','event','tcp_content'],
        [u'Alarm TCP Port','event','tcpudp_service'],
        [u'Alarm Verify Operational','event','interface_protocol,,180'],
        [u'Alarm Reachability','event','reachability'],
        [u'Application Alarm','event','application'],
        [u'Alteon Admin Status','admin_status','down=0|up=2,2'],
        [u'Alarm Alteon RServer','event','alteon_rserver'],
        [u'Alarm Alteon Service','event','alteon_service'],
        [u'Alarm Alteon VServer','event','alteon_vserver'],
        [u'Brocade FC Admin View','admin_status','down=2|up=1,0'],
        [u'Change Interface Number','verify_index',''],
        [u'Alarm OS/400','event','os400_error'],
        ]

poller_sets = [
        [u'No Polling', u'No Interface Type', []],
        [u'Cisco Interface', u'Physical Interfaces', [
            [u'SNMP Verify Interface Number', u'Change Interface Number'],
#            [u'Cisco SNMP Ping Start', u''],
            [u'SNMP Interface Operational Status', u'Alarm Verify Operational'],
            [u'SNMP Interface Administrative Status', u'Set Admin Status'],
            [u'SNMP Input Rate', u''],
            [u'SNMP Input Packets', u''],
            [u'SNMP Output Rate', u''],
            [u'SNMP Output Packets', u''],
            [u'SNMP Output Errors', u''],
            [u'SNMP Input Errors', u''],
            [u'SNMP Drops', u''],
#            [u'Cisco SNMP Ping Wait', u''],
#            [u'Cisco SNMP Ping Get PL', u''],
#            [u'Cisco SNMP Ping Get RTT', u''],
#            [u'Cisco SNMP Ping End', u''],
            ]],
        [u'Cisco Router', u'Cisco System Info', [
            [u'Cisco CPU Utilization', u''],
            [u'TCP MIB Established Connections', u''],
            [u'Cisco Used Memory', u''],
            [u'TCP MIB Active Opens', u''],
            [u'Cisco Free Memory', u''],
            [u'TCP MIB Passive Opens', u''],
            ]],
        [u'TCP/IP Port', u'TCP Ports', [
            [u'TCP Port Check & Delay', u''],
            [u'TCP Port Status', u'Alarm TCP Port'],
            [u'TCP MIB Established', u''],
            [u'TCP Content Check', u'Alarm TCP Content']
            ]],
        [u'BGP Neighbor', u'BGP Neighbors', [
            [u'BGP Peer Status', u'Alarm BGP Peer' ],
            [u'BGP Inbound Updates', u''],
            [u'BGP Accepted Routes', u''],
            [u'BGP Advertised Routes', u''],
            [u'BGP Outbound Updates', u''],
            [u'BGP Uptime', u'']
            ]],
        [u'Storage Device', u'Storage', [
            [u'Verify Storage Index', u'Change Interface Number'],
            [u'Storage Device Block Size', u''],
            [u'Storage Device Total Blocks', u''],
            [u'Storage Device Used Blocks', u'']
            ]],
        [u'Linux/Unix Host', u'Linux/Unix System Info', [
            [u'CPU Nice Time', u''],
            [u'Host MIB Number of Processes', u''],
            [u'CPU User Time', u''],
            [u'Host MIB Number of Users', u''],
            [u'CPU Idle Time', u''],
            [u'TCP MIB Established Connections', u''],
            [u'CPU System Time', u''],
            [u'TCP MIB Active Opens', u''],
            [u'Load Average 1 min', u''],
            [u'TCP MIB Passive Opens', u''],
            [u'Load Average 5 min', u''],
            [u'Load Average 15 min', u'']
            ]],
        [u'Solaris Host', u'Solaris System Info', [
            [u'CPU System Time', u''],
            [u'CPU Idle Time', u''],
            [u'CPU Kernel Time', u''],
            [u'CPU Wait Time', u''],
            [u'Load Average 1 min', u''],
            [u'Load Average 5 min', u''],
            [u'Load Average 15 min', u''],
            [u'Real Memory Available', u''],
            [u'Real Memory Total', u''],
            [u'Swap Memory Available', u''],
            [u'Swap Memory Total', u''],
            ]],
        [u'Windows Host', u'Windows System Info', [
            [u'Host MIB Proc Average Util', u''],
            [u'Host MIB Number of Processes', u''],
            [u'Host MIB Number of Users', u''],
            [u'TCP MIB Active Opens', u''],
            [u'TCP MIB Established Connections', u''],
            [u'TCP MIB Passive Opens', u'']
            ]],
        [u'HostMIB Application', u'Applications', [
            [u'Host MIB Process Verifier', u''],
            [u'Host MIB Status', u'Application Alarm'],
            [u'Host MIB Process Memory Usage', u'']
            ]],
        [u'Cisco Power Supply', u'Cisco Power Supply', [
            [u'Cisco Power Supply Status', u'Alarm Environmental'],
            ]],
        [u'Cisco Temperature', u'Cisco Temperature', [
            [u'Cisco Temperature Status', u'Alarm Environmental'],
            [u'Cisco Temperature', u'']
            ]],
        [u'Cisco Voltage', u'Cisco Voltage', [
            [u'Cisco Voltage Status', u'Alarm Environmental'],
            ]],
        [u'Cisco SA Agent', u'Cisco SA Agent', [
            [u'SA Agent Forward Jitter', u''],
            [u'SA Agent Backward Jitter', u''],
            [u'SA Agent Packetloss', u''],
            ]],
        [u'Reachability', u'Reachable', [
            [u'Reachability Ping', u''],
            [u'Reachability Status', u'Alarm Reachability'],
            ]],
        [u'NTP', u'NTP', [
            [u'NTP Status', u'Alarm NTP'],
            ]],
        [u'Compaq Physical Drive', u'Compaq Physical Drives', [
            [u'Compaq Drive Condition', u'Alarm Environmental'],
            ]],
        [u'Compaq Fan', u'Compaq Fans', [
            [u'Compaq Fan Condition', u'Alarm Environmental'],
            ]],
        [u'Compaq Temperature', u'Compaq Temperature', [
            [u'Compaq Temperature Status', u'Alarm Environmental'],
            [u'Compaq Temperature', u'']
            ]],
        [u'IIS Info', u'IIS Webserver Information', [
            [u'IIS Total Bytes Received', u''],
            [u'IIS Total CGI Requests', u''],
            [u'IIS Total Files Sent', u''],
            [u'IIS Total GETs', u''],
            [u'IIS Total Posts', u'']
            ]],
        [u'Apache', u'Apache', [
            [u'Apache Status', u''],
            ]],
        [u'APC', u'APC', [
            [u'APC Battery Status', u'Alarm Environmental' ],
            [u'APC Output Status', u'Alarm APC' ],
            [u'APC Battery Capacity', u''],
            [u'APC Output Load', u''],
            [u'APC Input Voltage', u''],
            [u'APC Output Voltage', u''],
            [u'APC Time Remaining', u''],
            [u'APC Temperature', u'']
            ]],
        [u'Alteon Real Server', u'Alteon Real Server', [
            [u'Alteon RServer Admin', u'Alteon Admin Status'],
            [u'Alteon RServer Oper', u'Alarm Verify Operational'],
            [u'Alteon RServer Current Sessions', u''],
            [u'Alteon RServer Failures', u''],
            [u'Alteon RServer Octets', u''],
            [u'Alteon RServer Total Sessions', u'']
            ]],
        [u'Alteon Virtual Server', u'Alteon Virtual Server', [
            [u'Alteon VServer Admin State', u'Set Admin Status'],
            [u'Alteon VServer Current Sessions', u''],
            [u'Alteon VServer Octets', u''],
            [u'Alteon VServer Total Sessions', u'']
            ]],
        [u'Alteon Real Services', u'Alteon Real Services', [
            [u'Alteon RService Admin State', u'Set Admin Status'],
            [u'Alteon RService Oper State', u'Alarm Alteon Service'],
            [u'Alteon RService Response Time', u'']
            ]],
        [u'Alteon System Info', u'Alteon System Info', [
            [u'Alteon CPU A 1Sec', u''],
            [u'Alteon CPU A 4Secs', u''],
            [u'Alteon CPU A 64Secs', u''],
            [u'Alteon CPU B 1Sec', u''],
            [u'Alteon CPU B 4Secs', u''],
            [u'Alteon CPU B 64Secs', u''],
            [u'TCP MIB Active Opens', u''],
            [u'TCP MIB Passive Opens', u''],
            [u'TCP MIB Established Connections', u''],
            [u'Alteon Memory Used', u''],
            [u'Alteon Memory Total', u'']
            ]],
        [u'Brocade Sensors', u'Brocade Sensors', [
            [u'Brocade Sensor Oper', u'Alarm Verify Operational'],
            [u'Brocade Sensor Value', u''],
            ]],
        [u'Brocade FC Ports', u'Brocade FC Ports', [
            [u'Brocade FC Port Admin State', u'Brocade FC Admin View'],
            [u'Brocade FC Port Oper Status', u'Alarm Verify Operational'],
            [u'Brocade FC Port Phy State', u'Alarm Brocade FC Port'],
            [u'Brocade FC Port TxWords', u''],
            [u'Brocade FC Port RxWords', u''],
            [u'Brocade FC Port TxFrames', u''],
            [u'Brocade FC Port RxFrames', u'']
            ]],
        [u'UPS', u'UPS', [
            [u'UPS Battery Status', u'Alarm Environmental'],
            [u'UPS Battery Charge Remaining', u''],
            [u'UPS Battery Minutes Remaining', u''],
            [u'UPS Battery Temperature', u'']
            ]],
        [u'UPS Input Line', u'UPS Input Line', [
            [u'UPS Input Voltage', u''],
            [u'UPS Input Current', u''],
            ]],
        [u'UPS Output Line', u'UPS Output Line', [
            [u'UPS Output Voltage', u''],
            [u'UPS Output Current', u''],
            [u'UPS Output Load', u''],
            ]],
        [u'Mitsubishi UPS Input Line', u'Mitsubishi UPS Input Line', [
            [u'Mitsu UPS Input Voltage', u''],
            [u'Mitsu UPS Input Current', u''],
            [u'Mitsu UPS Input Power', u''],
            ]],
        [u'Mitsubishi UPS Output Line', u'Mitsubishi UPS Output Line', [
            [u'Mitsu UPS Output Voltage', u''],
            [u'Mitsu UPS Output Current', u''],
            [u'Mitsu UPS Output Load', u''],
            [u'Mitsu UPS Output Power', u'']
            ]],
        [u'PIX Connection Stat', u'Cisco PIX', [
            [u'Pix Connections Poller', u''],
            ]],
        [u'Cisco NAT', u'Cisco NAT', [
            [u'Cisco NAT Other IP Outbound', u''],
            [u'Cisco NAT Other IP Inbound', u''],
            [u'Cisco NAT ICMP Outbound', u''],
            [u'Cisco NAT ICMP Inbound', u''],
            [u'Cisco NAT UDP Outbound', u''],
            [u'Cisco NAT UDP Inbound', u''],
            [u'Cisco NAT TCP Outbound', u''],
            [u'Cisco NAT TCP Inbound', u''],
            [u'Cisco NAT Active Binds', u'']
            ]],
        [u'Sensors', u'Sensors', [
            [u'Verify Sensor Index', u'Change Interface Number'],
            [u'Sensor Value', u''],
            ]],
        [u'OS/400 Host', u'OS/400 System Info', [
            [u'OS 400 System Load', u''],
            ]],
        [u'Dell Chassis', u'Dell Chassis', [
            [u'Dell OpenManage Chassis', u'Alarm Verify Operational'],
            [u'Dell OpenManage Chassis' ,u'Set Admin Status'],
            [u'Dell OpenManage Ambient Temp', u''],
            [u'Dell OpenManage Fan RPM #1', u''],
            [u'Dell OpenManage Fan RPM #2', u''],
            [u'Dell OpenManage Fan RPM #3', u''],
            [u'Dell OpenManage Fan RPM #4', u''],
            [u'Dell OpenManage Fan RPM #5', u''],
            [u'Dell OpenManage Fan RPM #6', u''],
            [u'Dell OpenManage Fan RPM #7', u''],
            ]],
        [u'Compaq Power Supply', u'Compaq Power Supply', [
            [u'Compaq Power Condition', u'Alarm Environmental'],
            ]],
        [u'Cisco 802.11X Device', u'Cisco 802.11X Device', [
            [u'802.11x Associated Clients', u''],
            ]],
        [u'Fibre Channel Interface', u'Generic FC Ports', [
            [u'FC Oper Status', u'Alarm Environmental'],
            [u'FCPort RxFrames', u''],
            [u'FCPort TxFrames', u''],
            ]],
        [u'SNMP Interface', u'Physical Interfaces', [
            [u'SNMP Verify Interface Number', u'Change Interface Number'],
            [u'SNMP Interface Operational Status', u'Alarm Verify Operational'],
            [u'SNMP Interface Administrative Status', u'Set Admin Status'],
            [u'SNMP Input Rate', u''],
            [u'SNMP Input Packets', u''],
            [u'SNMP Output Rate', u''],
            [u'SNMP Output Packets', u''],
            [u'SNMP Output Errors', u''],
            [u'SNMP Input Errors', u''],
            [u'SNMP Drops', u''],
            ]],
        ]

graph_types = [
        [u'Traffic', 'Physical Interfaces', '', u'bps', '',
            [ #DEF
                ['input', 'input'],
                ['output', 'output'],
            ],[ #vnames
                ['CDEF', 'inputbits', 'input,UN,input,input,IF,8,*'],
                ['CDEF', 'outputbits', 'output,UN,output,output,IF,8,*'],
                ['VDEF', 'inputmax', 'inputbits,MAXIMUM'],
                ['VDEF', 'inputavg', 'inputbits,AVERAGE'],
                ['VDEF', 'inputlast', 'inputbits,LAST'],
                ['VDEF', 'outputmax', 'outputbits,MAXIMUM'],
                ['VDEF', 'outputavg', 'outputbits,AVERAGE'],
                ['VDEF', 'outputlast', 'outputbits,LAST'],
            ],[ #lines
                ['HRULE', 'speed', 'CC0000', 'Bandwidth ${speed_units}bps\l'],
                ['AREA', 'inputbits', '00CC00', ' Inbound\\n', False],
                ['PRINT', 'inputmax', 'Max: %6.2lf%S'],
                ['PRINT', 'inputavg', 'Avg: %6.2lf%S'],
                ['PRINT', 'inputlast', r'Cur: %6.2lf%S\l'],
                ['LINE', 'outputbits', '0000CC', 2, 'Outbound (bps)'],
                ['PRINT', 'outputmax', 'Max: %6.2lf%S'],
                ['PRINT', 'outputavg', 'Avg: %6.2lf%S'],
                ['PRINT', 'outputlast', 'Cur: %6.2lf%S\l'],
            ] ],
        [u'Utilization', 'Physical Interfaces', 'Utilization', u'%', '',
            [ #DEF
                ['input', 'input'],
                ['output', 'output'],
            ],[ #vnames
                ['CDEF', 'input_pct', 'input,UN,0,input,IF,800,*,$speed,/'],
                ['CDEF', 'output_pct', 'output,UN,0,output,IF,800,*,$speed,/'],
                ['VDEF', 'inputmax', 'input_pct,MAXIMUM'],
                ['VDEF', 'inputavg', 'input_pct,AVERAGE'],
                ['VDEF', 'inputlast', 'input_pct,LAST'],
                ['VDEF', 'outputmax', 'output_pct,MAXIMUM'],
                ['VDEF', 'outputavg', 'output_pct,AVERAGE'],
                ['VDEF', 'outputlast', 'output_pct,LAST'],
            ],[ #lines
                ['HRULE', '100', 'CC0000', None],
                ['AREA', 'input_pct', '00CC00', ' Input\\n', False],
                ['PRINT', 'inputmax', 'Max: %5.1lf%%'],
                ['PRINT', 'inputavg', 'Avg: %5.1lf%%'],
                ['PRINT', 'inputlast', r'Cur: %5.1lf%%\l'],
                ['LINE', 'output_pct', '0000CC', 2, 'Output'],
                ['PRINT', 'outputmax', 'Max: %5.1lf%%'],
                ['PRINT', 'outputavg', 'Avg: %5.1lf%%'],
                ['PRINT', 'outputlast', 'Cur: %5.1lf%%\l'],
            ] ],
        [u'Packets', 'Physical Interfaces', '', u'Pps', '',
            [ #DEF
                ['input', 'inpackets'],
                ['output', 'outpackets'],
            ],[ #vnames
                ['VDEF', 'inputmax', 'input,MAXIMUM'],
                ['VDEF', 'inputavg', 'input,AVERAGE'],
                ['VDEF', 'inputlast', 'input,LAST'],
                ['VDEF', 'outputmax', 'output,MAXIMUM'],
                ['VDEF', 'outputavg', 'output,AVERAGE'],
                ['VDEF', 'outputlast', 'output,LAST'],
            ],[ #lines
                ['AREA', 'input', '00CC00', ' Input Packets\n', False],
                ['PRINT', 'inputmax', 'Max: %6.2lf%S'],
                ['PRINT', 'inputavg', 'Avg: %6.2lf%S'],
                ['PRINT', 'inputlast', r'Cur: %6.2lf%S\l'],
                ['LINE', 'output', '0000CC', 2, 'Output Packets'],
                ['PRINT', 'outputmax', 'Max: %6.2lf%S'],
                ['PRINT', 'outputavg', 'Avg: %6.2lf%S'],
                ['PRINT', 'outputlast', 'Cur: %6.2lf%S\l'],
            ] ],
        [u'Packets New', 'Physical Interfaces', '', u'Pps', '',
            [ #DEF
                ['inpackets', 'inpackets'],
                ['outpackets', 'outpackets'],
                ['inputerrors', 'inputerrors'],
                ['outputerrors', 'outputerrors'],
            ],[ #vnames
                ['CDEF', 'input', 'inpackets,UN,0,inpackets,IF'],
                ['CDEF', 'output', 'outpackets,UN,0,outpackets,IF'],
                ['CDEF', 'inputerr', 'inputerrors,UN,0,inputerrors,IF'],
                ['CDEF', 'outputerr', 'outputerrors,UN,0,outputerrors,IF'],
                ['CDEF', 'outputrev', 'output,-1,*'],
                ['CDEF', 'totin', 'input,inputerr,+'],
                ['CDEF', 'totout', 'output,outputerr,+'],

                ['CDEF', 'inpct1', 'input,100,*,totin,/'],
                ['CDEF', 'outpct1', 'output,100,*,totout,/'],

                ['CDEF', 'inpct', 'inpct1,UN,100,inpct1,IF'],
                ['CDEF', 'outpct', 'outpct1,UN,100,outpct1,IF'],

                ['CDEF', 'ierrpct1', 'inputerr,100,*,totin,/,0.01,100,LIMIT'],
                ['CDEF', 'oerrpct1', 'outputerr,100,*,totout,/,0.01,100,LIMIT'],

                ['CDEF', 'ierrpct', 'ierrpct1,UN,0,ierrpct1,IF'],
                ['CDEF', 'oerrpct', 'oerrpct1,UN,0,oerrpct1,IF'],

                ['VDEF', 'inputmax', 'input,MAXIMUM'],
                ['VDEF', 'inputavg', 'input,AVERAGE'],
                ['VDEF', 'inputlast', 'input,LAST'],
                ['VDEF', 'inpctmax', 'inpct,MAXIMUM'],
                ['VDEF', 'inpctavg', 'inpct,AVERAGE'],
                ['VDEF', 'inpctlast', 'inpct,LAST'],

                ['VDEF', 'inerrmax', 'inputerr,MAXIMUM'],
                ['VDEF', 'inerravg', 'inputerr,AVERAGE'],
                ['VDEF', 'inerrlast', 'inputerr,LAST'],
                ['VDEF', 'inerrpctmax', 'ierrpct,MAXIMUM'],
                ['VDEF', 'inerrpctavg', 'ierrpct,AVERAGE'],
                ['VDEF', 'inerrpctlast', 'ierrpct,LAST'],

                ['VDEF', 'outputmax', 'output,MAXIMUM'],
                ['VDEF', 'outputavg', 'output,AVERAGE'],
                ['VDEF', 'outputlast', 'output,LAST'],
                ['VDEF', 'outpctmax', 'outpct,MAXIMUM'],
                ['VDEF', 'outpctavg', 'outpct,AVERAGE'],
                ['VDEF', 'outpctlast', 'outpct,LAST'],

                ['VDEF', 'outerrmax', 'outputerr,MAXIMUM'],
                ['VDEF', 'outerravg', 'outputerr,AVERAGE'],
                ['VDEF', 'outerrlast', 'outputerr,LAST'],
                ['VDEF', 'outerrpctmax', 'oerrpct,MAXIMUM'],
                ['VDEF', 'outerrpctavg', 'oerrpct,AVERAGE'],
                ['VDEF', 'outerrpctlast', 'oerrpct,LAST'],
            ],[ #lines
                ['AREA', 'input', '00CC00', 'Input  Packets\n', False],
                ['PRINT', 'inputmax', r'%6.2lf%S\g'],
                ['PRINT', 'inpctmax', '(%5.1lf%%)\g'],
                ['PRINT', 'inputavg', r'%6.2lf%S\g'],
                ['PRINT', 'inpctavg', '(%5.1lf%%)\g'],
                ['PRINT', 'inputlast', r'%6.2lf%S\g'],
                ['PRINT', 'inpctlast', '(%5.1lf%%)\j'],
                ['AREA', 'ierrpct', 'FF0000', r'Input  Errors \g', True],
                ['PRINT', 'inerrmax', r'%6.2lf%S\g'],
                ['PRINT', 'inerrpctmax', '(%5.1lf%%)\g'],
                ['PRINT', 'inerravg', r'%6.2lf%S\g'],
                ['PRINT', 'inerrpctavg', '(%5.1lf%%)\g'],
                ['PRINT', 'inerrlast', r'%6.2lf%S\g'],
                ['PRINT', 'inerrpctlast', '(%5.1lf%%)\j'],

                ['AREA', 'outputrev', '0000FF', 'Output Packets\n', False],
                ['PRINT', 'outputmax', '%6.2lf%S\g'],
                ['PRINT', 'outpctmax', '(%5.1lf%%)\g'],
                ['PRINT', 'outputavg', '%6.2lf%S\g'],
                ['PRINT', 'outpctavg', '(%5.1lf%%)\g'],
                ['PRINT', 'outputlast', '%6.2lf%S\g'],
                ['PRINT', 'outpctlast', '(%5.1lf%%)\j'],
                ['AREA', 'oerrpct', 'AA0000', 'Output Errors \g', True],
                ['PRINT', 'outerrmax', '%6.2lf%S\g'],
                ['PRINT', 'outerrpctmax', '(%5.1lf%%)\g'],
                ['PRINT', 'outerravg', '%6.2lf%S\g'],
                ['PRINT', 'outerrpctavg', '(%5.1lf%%)\g'],
                ['PRINT', 'outerrlast', '%6.2lf%S\g'],
                ['PRINT', 'outerrpctlast', '(%5.1lf%%)\j'],

            ] ],
        [u'Errors', 'Physical Interfaces', '', u'Errors/sec', '',
            [ #DEF
                ['input', 'inputerrors'],
                ['output', 'outputerrors'],
            ],[ #vnames
                ['VDEF', 'inputavg', 'input,AVERAGE'],
                ['VDEF', 'inputlast', 'input,LAST'],
                ['VDEF', 'outputavg', 'output,AVERAGE'],
                ['VDEF', 'outputlast', 'output,LAST'],
            ],[ #lines
                ['AREA', 'input', '00CC00', ' Input Errors\\n', False],
                ['PRINT', 'inputavg', 'Input Errors :- Average: %4.0lf %sEps'],
                ['PRINT', 'inputlast', r'Current: %4.0lf %sEps\l'],
                ['LINE', 'output', '0000CC', 2, 'Output Errors'],
                ['PRINT', 'outputavg', 'Output Errors :- Average: %4.0lf %sEps'],
                ['PRINT', 'outputlast', 'Current: %4.0lf %sEps\l'],
            ] ],
        
            
        [u'Hits', 'Apache', '', u'Hits', '',
            [ #DEF
                ['tac', 'tac'],
            ],[ #vnames
                ['VDEF', 'tacmax', 'tac,MAXIMUM'],
                ['VDEF', 'tacavg', 'tac,AVERAGE'],
                ['VDEF', 'taclast', 'tac,LAST'],
            ],[ #lines
                ['LINE', 'tac', '0000CC', 2, 'Hits per Second'],
                ['PRINT', 'tacmax', 'Maximum: %8.0lf %sHits/s'],
                ['PRINT', 'tacavg', 'Average: %8.0lf %sHits/s'],
                ['PRINT', 'taclast', 'Current: %8.0lf %sHits/s\l'],
            ]
        ],
        [u'Throughput', 'Apache', '', u'Bytes/Sec', '',
            [ #DEF
                ['tkb', 'tkb'],
            ],[ #vnames
                ['CDEF', 'bytes', 'tkb,1000,*'],
                ['VDEF', 'bytesmax', 'bytes,MAXIMUM'],
                ['VDEF', 'bytesavg', 'bytes,AVERAGE'],
                ['VDEF', 'byteslast', 'bytes,LAST'],
            ],[ #lines
                ['LINE', 'bytes', '0000CC', 2, ''],
                ['PRINT', 'bytesmax', 'Maximum: %8.0lf %sBps'],
                ['PRINT', 'bytesavg', 'Average: %8.0lf %sBps'],
                ['PRINT', 'byteslast', 'Current: %8.0lf %sBps\l'],
            ]
        ],
        [u'CPU Load', 'Apache', '', u'Bytes/Sec', '',
            [ #DEF
                ['up', 'up'],
                ['load', 'cplo'],
            ],[ #vnames
                ['VDEF', 'loadmax', 'load,MAXIMUM'],
                ['VDEF', 'loadavg', 'load,AVERAGE'],
                ['VDEF', 'loadlast', 'load,LAST'],
                ['VDEF', 'uplast', 'up,LAST'],
            ],[ #lines
                ['LINE', 'load', '0000CC', 2, ''],
                ['PRINT', 'uplast', 'Uptime  -  %.0lf %s seconds\l'],
                ['PRINT', 'loadmax', 'CPU Load - Maximum: %.3lf'],
                ['PRINT', 'loadavg', 'Average: %.3lf'],
                ['PRINT', 'loadlast', 'Current: %.3lf\l'],
            ]
        ],
        [u'Bytes/Req', 'Apache', '', u'Bytes/Req', '',
            [ #DEF
                ['bpr', 'bpr'],
            ],[ #vnames
                ['VDEF', 'bprmax', 'bpr,MAXIMUM'],
                ['VDEF', 'bpravg', 'bpr,AVERAGE'],
                ['VDEF', 'bprlast', 'bpr,LAST'],
            ],[ #lines
                ['LINE', 'bpr', '0000CC', 2, 'Bytes/Request'],
                ['PRINT', 'bprmax', 'Maximum: %.0lf %s'],
                ['PRINT', 'bpravg', 'Average: %.0lf %s'],
                ['PRINT', 'bprlast', 'Current: %.0lf %s\l'],
            ]
        ],
        [u'Workers', 'Apache', '', u'Workers', 'lower-limit=0',
            [ #DEF
                ['bw', 'bw'],
                ['iw', 'iw'],
            ],[ #vnames
                ['VDEF', 'bwmax', 'bw,MAXIMUM'],
                ['VDEF', 'bwavg', 'bw,AVERAGE'],
                ['VDEF', 'bwlast', 'bw,LAST'],
                ['VDEF', 'iwmax', 'iw,MAXIMUM'],
                ['VDEF', 'iwavg', 'iw,AVERAGE'],
                ['VDEF', 'iwlast', 'iw,LAST'],
            ],[ #lines
                ['HRULE', '0', '000000', ''],
                ['AREA', 'bw', 'DD2200', r'Busy Workers\l'],
                ['AREA', 'iw', '00CC00', 'Idle Workers\l', True],
                ['PRINT', 'bwmax', r'Workers (busy:idle) - Maximum: %.0lf:\g'],
                ['PRINT', 'iwmax', r'%.0lf'],
                ['PRINT', 'bwavg', r'Average: %.0lf:\g'],
                ['PRINT', 'iwavg', r'%.0lf'],
                ['PRINT', 'bwlast', r'Current: %.0lf:\g'],
                ['PRINT', 'iwlast', r'%.0lf'],
            ]
        ],
        
        [u'Sensor Value', 'Sensors', '$measure', u'$unit', '',
            [ #DEF
                ['value', 'value'],
            ],[ #vnames
                ['CDEF', 'valk', 'value,${multiplier},*',],
                ['VDEF', 'vmax', 'valk,MAXIMUM'],
                ['VDEF', 'vavg', 'valk,AVERAGE'],
                ['VDEF', 'vlast', 'valk,LAST'],
            ],[ #lines
                ['LINE', 'valk', '0000ff', 2, r'${measure}\l'],
                ['PRINT', 'vmax', r'$measure - Maximum: %.2lf %S${units}'],
                ['PRINT', 'vavg', r'Average: %.2lf %S${units}'],
                ['PRINT', 'vlast', r'Current: %.2lf %S${units}\l'],
            ]
        ],
    ] # end of graph types

triggers = (
        (
        u'Interface Status Change', 'alarm', False, True, u'${attribute} ${state}', 
        u'The attribute ${attribute} is ${state} on host ${host}.', ( #rules
            ('event_type', '!IN', 'sla,admin', False, False),
            )),
    ) # end oftriggers

snmp_enterprises = (
        (2, u'IBM', 0, ()),
        (9, u'Cisco', 2, (
            ('45', u'7507'),
            ('46', u'7513'),
            ('47', u'7506'),	
            ('48', u'7505'),
            ('109', u'AS5200'),
            ('153', u'AS2509RJ'),
            ('185', u'2610'),			
            ('186', u'2611'),			
            ('187', u'2612'),			
            ('188', u'AS5800'),
            ('191', u'UBR904'),			
            ('200', u'1710'),
            ('201', u'1720'),		
            ('209', u'2621'),			
            ('210', u'UBR 7223'),		
            ('211', u'6400Nrp'),		
            ('212', u'801'),			
            ('213', u'802'),			
            ('214', u'803'),			
            ('215', u'804'),			
            ('216', u'1750'),			
            ('217', u'2924XLv'),			
            ('218', u'2924CXLv'),			
            ('219', u'2912XL'),			
            ('220', u'2924MXL'),			
            ('221', u'2912MfXL'),			
            ('222', u'7206VXR'),		
            ('223', u'7204VXR'),		
            ('227', u'PIXFirewall'),		
            ('228', u'MGX8850'),		
            ('229', u'MGX8830'),		
            ('244', u'LocalDirector'),	
            ('245', u'805'),			
            ('249', u'1407'),			
            ('250', u'1417'),			
            ('251', u'6100'),			
            ('252', u'6130'),			
            ('253', u'6260'),			
            ('254', u'OpticalRegenerator'),	
            ('255', u'UBR924'),		
            ('256', u'WSX6302Msm'),             
            ('257', u'5k RSFC'),
            ('258', u'6k MSFC'),
            ('271', u'UBR 7246VXR'),           
            ('272', u'10400'),		
            ('273', u'12016'),		
            ('274', u'As5400'),		
            ('276', u'7140Octt1'),		
            ('277', u'7140Dualfe'),		
            ('279', u'VG200'),		
            ('280', u'Cat 6006'),
            ('281', u'Cat 6009'),
            ('282', u'Cat 6506'),
            ('283', u'Cat 6509'),
            ('284', u'827'),			
            ('288', u'7507z'),		
            ('289', u'7513z'),		
            ('290', u'7507mx'),		
            ('291', u'7513mx'),		
            ('292', u'UBR912C'),		
            ('293', u'UBR912S'),		
            ('294', u'UBR914'),		
            ('295', u'802J'),			
            ('296', u'804J'),			
            ('297', u'6160'),			
            ('299', u'6015'),			
            ('300', u'6k MSFC2'),
            ('308', u'AS 5850'),		
            ('310', u'6509 SP'),		
            ('313', u'AS5350'),		
            ('314', u'7750'),		
            ('315', u'MGX8950'),		
            ('316', u'UBR925'),		
            ('317', u'UBR10012'),	
            ('319', u'2650'),		
            ('320', u'2651'),		
            ('321', u'826QuadV'),	
            ('322', u'826'),		
            ('323', u'2950-12'),
            ('324', u'2950-24'),
            ('325', u'2950-24C'),
            ('326', u'1751'),		
            ('329', u'626'),		
            ('330', u'627'),		
            ('331', u'633'),		
            ('332', u'673'),		
            ('333', u'675'),		
            ('334', u'675e'),		
            ('335', u'676'),		
            ('336', u'677'),		
            ('337', u'678'),		
            ('338', u'3661Ac'),		
            ('339', u'3661Dc'),		
            ('340', u'3662Ac'),		
            ('341', u'3662Dc'),		
            ('342', u'3662AcCo'),		
            ('343', u'3662DcCo'),		
            ('344', u'UBR7111'),	
            ('345', u'UBR7111E'),	
            ('346', u'UBR7114'),	
            ('347', u'UBR7114E'),	
            ('348', u'12010'),	
            ('349', u'8110'),	
            ('351', u'UBR905'),	
            ('353', u'SOHO77'),    
            ('354', u'SOHO76'),    
            ('371', u'CVA122E'),	
            ('372', u'CVA124E'),	
            ('376', u'7401VXR'),	
            ('382', u'828'),
            ('384', u'806'),
            ('389', u'PIX 506'),
            ('390', u'PIX 515'),
            ('391', u'PIX 520'),
            ('392', u'PIX 525'),
            ('393', u'PIX 535'),
            ('395', u'811'),
            ('396', u'813'),
            ('401', u'7603'),
            ('402', u'7606'),
            ('444', u'1721'),
            ('448', u'4006'),
            ('450', u'PIX 506E'),
            ('451', u'PIX 515E'),
            ('466', u'2610XM'),     
            ('467', u'2611XM'),     
            ('468', u'2620XM'),     
            ('469', u'2621XM'),     
            ('470', u'2650XM'),     
            ('471', u'2651XM'),     
            ('497', u'831'),     
            ('499', u'836'),     
            ('509', u'7609'),
            ('511', u'3750-24'),
            ('512', u'3750-48'),
            ('513', u'3750-24TS'),
            ('514', u'3750-24T'),
            ('516', u'3750 Stack'),
            ('535', u'3750-48PS'),
            ('536', u'3750-24PS'),
            ('538', u'1711'),
            ('539', u'1712'),
            ('557', u'Cat6k Sup720'),
            ('558', u'VG224'),
            ('559', u'2950-48T'),
            ('560', u'2950-48SX'),
            ('561', u'2970-24TS'),
            ('565', u'Aironet 3100'),
            ('566', u'851'),
            ('567', u'857'),
            ('568', u'876'),
            ('569', u'877'),
            ('570', u'878'),
            ('571', u'871'),
            ('576', u'2811'),
            ('577', u'2821'),
            ('578', u'2851'),
            ('602', u'3750G2-24PS'),
            ('603', u'3750G2-48PS'),
            ('604', u'3750G2-48TS'),
            ('613', u'CRS16S'),
            ('614', u'3560G2-24PS'),
            ('615', u'3560G2-24TS'),
            ('616', u'3560G2-48PS'),
            ('617', u'3560G2-48TS'),
            ('618', u'Aironet 1130'),
            ('619', u'2801'),
            ('620', u'1841'),
            ('633', u'3560-24TS'),
            ('634', u'3560-48TS'),
            ('638', u'1801'),
            ('639', u'1802'),
            ('640', u'1803'),
            ('641', u'1811'),
            ('642', u'1812'),
            ('643', u'CRS8S'),
            ('669', u'ASA5510'),
            ('670', u'ASA5520'),
            ('671', u'ASA5520sc'),
            ('672', u'ASA5540'),
            ('673', u'ASA5540sc'),
            ('694', u'2960-24'),
            ('695', u'2960-48'),
            ('696', u'2960G-24'),
            ('697', u'2960G-48'),
            ('716', u'2960-24TT'),
            ('717', u'2960-48TT'),
            ('745', u'ASA5505'),
            ('753', u'ASA5550'),
            ('843', u'886G'), 
            ('844', u'Iad886F'), 
            ('845', u'Iad886B'), 
            ('846', u'886Srst'), 
            ('847', u'887'), 
            ('848', u'887G'), 
            ('963', u'VG204'), 
            ('964', u'VG202'), 
            ('1041', u'3945'), 
            ('1042', u'3925'), 
            ('1043', u'2951'), 
            ('1044', u'2921'), 
            ('1045', u'2911'), 
            ('1046', u'2901'), 
            ('1047', u'1941'), 
            ('1048', u'Sm2k15Es1GePoe'), 
            ('1049', u'Sm3k15Es1GePoe'), 
            ('1050', u'Sm3k16GePoe'), 
            ('1051', u'Sm2k23Es1Ge'), 
            ('1052', u'Sm2k23Es1GePoe'), 
            ('1053', u'Sm3k23Es1GePoe'), 
            ('1054', u'Sm3k24GePoe'), 
            ('1055', u'SmXd2k48Es2SFP'), 
            ('1056', u'SmXd3k48Es2SFPPoe'), 
            ('1057', u'SmXd3k48Ge2SFPPoe'), 
            ('1058', u'Esw52024pK9'), 
            ('1059', u'Esw54024pK9'), 
            ('1060', u'Esw52048pK9'), 
            ('1061', u'Esw52024K9'), 
            ('1062', u'Esw54024K9'), 
            ('1063', u'Esw52048K9'), 
            ('1064', u'Esw54048K9'), 
            ('1065', u'1861'), 
            ('1066', u'UC520'), 
            ('1146', '2960-24LCS'),
            ('1147', '2960-24PCS'),
            ('1191', u'1921K9'), 
            ('1194', u'ASA5585Ssp10'), 
            ('1195', u'ASA5585Ssp20'), 
            ('1196', u'ASA5585Ssp40'), 
            ('1197', u'ASA5585Ssp60'), 
            ('1198', u'ASA5585Ssp10sc'), 
            ('1199', u'ASA5585Ssp20sc'), 
            ('1200', u'ASA5585Ssp40sc'), 
            ('1201', u'ASA5585Ssp60sc'), 
            ('1202', u'ASA5585Ssp10sy'), 
            ('1222', u'3750X-24'),
            ('1223', u'3750X-48'),
            ('1224', u'3750X-24P'),
            ('1225', u'3750X-48P'),
            ('1226', u'3560X-24'),
            ('1227', u'3560X-48'),
            ('1228', u'3560X-24P'),
            ('1229', u'3560X-48P'),
            ('1230', u'NMEAIR'), 
            ('1231', u'ACE30K9'), 
            ('1232', u'ASA5585SspIps10'), 
            ('1233', u'ASA5585SspIps20'), 
            ('1234', u'ASA5585SspIps40'), 
            ('1235', u'ASA5585SspIps60'), 
            ('1236', u'1841CK9'), 
            ('1237', u'2801CK9'), 
            ('1238', u'2811CK9'), 
            ('1239', u'2821CK9'), 
            ('1241', u'3825CK9'), 
            ('1242', u'3845CK9'), 
            ('1245', u'CGS252024TC'), 
            ('1246', u'CGS252016S8PC'), 
            ('1247', u'AIRAP1262'), 
            ('1248', u'AIRAP1261'), 
            ('1249', u'892F'), 
            ('1297', u'ECDS3100'), 
            ('1298', u'ECDS1100'), 
            ('1328', u'2928-24TCC'),
            ('1329', u'2928-48TCC'),
            )),
        (11,    u'HP', 0, ()),
        (42,    u'Sun', 0, ()),
        (43,    u'HP/3Com', 0, ()),
        (52,    u'Enterasys', 0, ()),
        (63,    u'Apple', 0, ()),
        (94,    u'Nokia', 0, ()),
        (106,   u'EMC', 0, ()),
        (111,   u'Oracle', 0, ()),
        (116,   u'Hitachi', 0, ()),
        (123,   u'Newbridge', 0, ()),
        (161,   u'Motorolla', 0, ()),
        (164,   u'RAD', 0, ()),
        (171,   u'D-Link', 0, ()),
        (191,   u'NCR', 0, ()),
        (193,   u'Ericsson', 0, ()),
        (207,   u'Allied Telesyn', 0, ()),
        (288,   u'EDS', 0, ()),
        (289,   u'Brocade', 0, ()),
        (297,   u'Fuji Xerox', 0, ()),
        (311,   u'Microsoft', 0, ()),
        (318,   u'APC', 0, ()),
        (370,   u'HP/3Com', 0, ()),
        (582,   u'Cisco', 0, ()),
        (872,   u'AVM', 0, ()),
        (1230,   u'McAfee', 0, ()),
        (1573,   u'McAfee', 0, ()),
        (1588,   u'Brocade', 0, ()),
        (1872,   u'Alteon', 0, ()),
        (2011,   u'Huawei', 0, ()),
        (2636,   u'Juniper', 5, (
            ('1',   u'M20'),
            ('2',   u'M20'),
            ('3',   u'M160'),
            ('4',   u'M10'),
            ('5',   u'M5'),
            ('6',   u'T640'),
            ('7',   u'T320'),
            ('8',   u'M40e'),
            ('9',   u'M320'),
            ('10',  u'M7i'),
            ('11',  u'M10i'),
            ('13',  u'J2300'),
            ('14',  u'J4300'),
            ('15',  u'J6300'),
            ('17',  u'TX'),
            ('18',  u'M120'),
            ('21',  u'MX960'),
            ('25',  u'MX480'),
            ('26',  u'SRX5800'),
            ('28',  u'SRX5600'),
            ('29',  u'MX240'),
            ('30',  u'EX3200'),
            ('31',  u'EX4200'),
            ('32',  u'EX8208'),
            ('33',  u'EX8216'),
            ('34',  u'SRX3600'),
            ('35',  u'SRX3400'),
            ('41',  u'SRX100'),
            ('42',  u'ESR1000V'),
            ('43',  u'EX2200'),
            ('44',  u'EX4500'),
            ('49',  u'SRX1400'),
            ('57',  u'MX80'),
            ('58',  u'SRX220'),
            ('59',  u'EX XRE'),
            ('60',  u'QFX Interconnect'),
            ('61',  u'QFX None'),
            ('64',  u'SRX1100'),

            )),
        (3401,   u'McAfee', 0, ()),
        (3902,   u'ZTE', 0, ()),
        (5771,   u'Cisco', 0, ()),
        (5842,   u'Cisco', 0, ()),
        (6876,   u'VMware', 0, ()),
        (7031,   u'McAfee', 0, ()),
        (8072, u'Net-SNMP', 3, (
            ('1', u'HP-UX 9'),
            ('2', u'SunOS 4'),
            ('3', u'Solaris'),
            ('4', u'OSF'),
            ('5', u'Ultrix'),
            ('6', u'HP-UX 10'),
            ('7', u'NetBSD'),
            ('8', u'FreeBSD'),
            ('9', u'Irix'),
            ('10', u'Linux'),
            ('11', u'BSDi'),
            ('12', u'OpenBSD'),
            ('13', u'Windows'),
            ('14', u'HP-UX 11'),
            ('15', u'AIX'),
            ('16', u'MacOS'),
            )),
        (11147, u'HP', 0, ()),
        (14823, u'Aruba', 0, ()),
        (22252, u'McAfee', 0, ()),
        (25506, u'H3C', 0, ()),
        (26484, u'Cisco', 0, ()),

        )


trap_matches = (
        (0, 'ifTable Link Down', '1.3.6.1.6.3.1.1.5.3', 'match_index_state', False, '1.3.6.1.2.1.2.2.1.1.5|down', u'Alarm Verify Operational'),
        (0, 'ifTable Link Up', '1.3.6.1.6.3.1.1.5.4', 'match_index_state', False, '1.3.6.1.2.1.2.2.1.1.5|down', u'Alarm Verify Operational'),
        )
